services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: restartcrm
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: restartcrm
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  python:
    image: python:3.10-slim
    container_name: restartcms
    environment:
      DB_USER: restartcrm
      DB_PASSWORD: changeme
      DB_NAME: restartcrm
      DB_HOST: postgres
      DB_PORT: 5432
      SECRET_KEY: changeme
      ALGORITHM: HS256
    ports:
      - "5000"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y git &&
        git clone https://github.com/bonniielll/RestartCRM.git /app &&
        cd /app &&
        rm -rf .venv &&
        python -m pip install -r requirements.txt &&
        python -m alembic revision --autogenerate &&
        python -m alembic upgrade head &&
        python -m uvicorn app.main:app --port 5000
      "
    restart: unless-stopped
