"""create tables

Revision ID: 04f1e8e05a68
Revises: 384ff1d5e823
Create Date: 2024-09-04 23:45:43.296793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04f1e8e05a68'
down_revision: Union[str, None] = '384ff1d5e823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('names', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('count_interactions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_revenue', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_payday', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
