"""create tables

Revision ID: 384ff1d5e823
Revises: 2e2cf642abf4
Create Date: 2024-09-04 21:55:17.126067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384ff1d5e823'
down_revision: Union[str, None] = '2e2cf642abf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('comment', sa.String(), nullable=False))
    op.add_column('newtrading', sa.Column('client_number', sa.String(), nullable=False))
    op.add_column('newtrading', sa.Column('akb', sa.String(), nullable=False))
    op.add_column('newtrading', sa.Column('method', sa.String(), nullable=False))
    op.add_column('newtrading', sa.Column('scrap_akb', sa.String(), nullable=False))
    op.add_column('newtrading', sa.Column('sum', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newtrading', 'sum')
    op.drop_column('newtrading', 'scrap_akb')
    op.drop_column('newtrading', 'method')
    op.drop_column('newtrading', 'akb')
    op.drop_column('newtrading', 'client_number')
    op.drop_column('clients', 'comment')
    op.drop_table('service')
    # ### end Alembic commands ###
