"""create users table

Revision ID: 36dbf22328de
Revises: 8a9e183c5b03
Create Date: 2024-09-08 11:05:29.438858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dbf22328de'
down_revision: Union[str, None] = '8a9e183c5b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newtrading', sa.Column('akb_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newtrading', 'akb_price')
    # ### end Alembic commands ###
