"""revision

Revision ID: 68cedb8006c7
Revises: 
Create Date: 2024-09-10 15:08:29.399023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cedb8006c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comissiontrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('akb_name', sa.String(), nullable=False),
    sa.Column('guarantee', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('scrap_akb', sa.String(), server_default=sa.text('0'), nullable=False),
    sa.Column('scrap_price', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('action_sum', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('sum', sa.Float(), nullable=False),
    sa.Column('method_pay', sa.String(), nullable=False),
    sa.Column('client', sa.String(), server_default=sa.text('0'), nullable=False),
    sa.Column('comment', sa.String(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comissiontrading')
    # ### end Alembic commands ###
