"""create tables

Revision ID: 752494929e18
Revises: 32d2553bef15
Create Date: 2024-09-10 00:19:03.334526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752494929e18'
down_revision: Union[str, None] = '32d2553bef15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('client_number', sa.String(), server_default=sa.text('0'), nullable=False),
    sa.Column('akb', sa.String(), nullable=False),
    sa.Column('akb_price', sa.Integer(), nullable=False),
    sa.Column('scrap_akb', sa.String(), nullable=False),
    sa.Column('scrap_price', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('action_sum', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('payment_invoice', sa.String(), nullable=False),
    sa.Column('invoice_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newtrading')
    # ### end Alembic commands ###
