"""Initial revision

Revision ID: b4b206d4aaaa
Revises: 
Create Date: 2024-09-05 14:39:34.525140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b206d4aaaa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('names', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('count_interactions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_revenue', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_payday', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('comissiontrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akb_name', sa.String(), nullable=False),
    sa.Column('guarantee', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('action_sum', sa.String(), nullable=True),
    sa.Column('sum', sa.String(), nullable=False),
    sa.Column('method_pay', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akb_name', sa.String(), nullable=False),
    sa.Column('client', sa.String(), nullable=False),
    sa.Column('when_broken', sa.String(), nullable=False),
    sa.Column('akb_docs', sa.String(), nullable=True),
    sa.Column('akb_place', sa.String(), nullable=False),
    sa.Column('comment_on_start', sa.String(), nullable=False),
    sa.Column('akb_on_switch', sa.String(), nullable=True),
    sa.Column('manager', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('tracker_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newtrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_number', sa.String(), nullable=False),
    sa.Column('akb', sa.String(), nullable=False),
    sa.Column('scrap_akb', sa.String(), nullable=False),
    sa.Column('scrap_price', sa.String(), nullable=False),
    sa.Column('action_sum', sa.String(), nullable=False),
    sa.Column('sum', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('payment_invoice', sa.String(), nullable=True),
    sa.Column('invoice_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraptrading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('ah_akb', sa.String(), nullable=False),
    sa.Column('sum', sa.String(), nullable=False),
    sa.Column('method_pay', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('mandarin_data', sa.String(), nullable=True),
    sa.Column('passport_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('akb_name', sa.String(), nullable=False),
    sa.Column('service_pay_sum', sa.String(), nullable=True),
    sa.Column('comment_before', sa.String(), nullable=True),
    sa.Column('akb_on_switch', sa.String(), nullable=True),
    sa.Column('deposit_for_switch_sum', sa.String(), nullable=True),
    sa.Column('comment_after', sa.String(), nullable=True),
    sa.Column('pay_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('scraptrading')
    op.drop_table('newtrading')
    op.drop_table('expertise')
    op.drop_table('comissiontrading')
    op.drop_table('clients')
    # ### end Alembic commands ###
