"""revision

Revision ID: b5e0be9b64ac
Revises: 82bcee464630
Create Date: 2024-09-14 16:22:50.207542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e0be9b64ac'
down_revision: Union[str, None] = '82bcee464630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expertise', 'market')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expertise', sa.Column('market', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
