"""create tables

Revision ID: c7621c1ed00a
Revises: 72fe87b54765
Create Date: 2024-09-08 22:05:46.163882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7621c1ed00a'
down_revision: Union[str, None] = '72fe87b54765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'account')
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('magazine', sa.String(), nullable=False))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_constraint('user_phone_number_key', 'user', type_='unique')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'email')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_phone_number_key', 'user', ['phone_number'])
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'magazine')
    op.drop_column('user', 'name')
    op.add_column('clients', sa.Column('account', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
