"""create tables

Revision ID: f1f419282739
Revises: 0b5c3c859999
Create Date: 2024-09-09 23:59:52.018637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f419282739'
down_revision: Union[str, None] = '0b5c3c859999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraprecording', sa.Column('where_move', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraprecording', 'where_move')
    # ### end Alembic commands ###
