name: Update Service via Webhook
run-name: Deploying...
on: [push]
jobs:
  Portainer-Webhook-Update:
    runs-on: ubuntu-latest
    steps:
      - uses: newarifrh/portainer-service-webhook@v1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}